name: Labels Blank issues

on:
  issues:
    types: [opened]

jobs:
  label-blank-issues:
    runs-on: ubuntu-latest
    if: github.repository == 'scikit-learn/scikit-learn'
    steps:
      - uses: andymckay/labeler@1.0.4
        with:
          add-labels: "Needs Triage"
          ignore-if-labeled: true
